export default [
  [
    { selected: '', shouldBe: 'grass' },
    { selected: '', shouldBe: 'grass' },
    { selected: '', shouldBe: 'grass' },
    { selected: '', shouldBe: 'grass' },
    { selected: '', shouldBe: 'grass' },
    { selected: '', shouldBe: 'grass' },
    { selected: '', shouldBe: 'tent' },
    { selected: '', shouldBe: 'grass' },
  ],
  [
    { selected: '', shouldBe: 'grass' },
    { selected: '', shouldBe: 'grass' },
    { selected: 'tree' },
    { selected: 'tree' },
    { selected: '', shouldBe: 'tent' },
    { selected: '', shouldBe: 'grass' },
    { selected: 'tree' },
    { selected: '', shouldBe: 'grass' },
  ],
  [
    { selected: '', shouldBe: 'tent' },
    { selected: 'tree' },
    { selected: '', shouldBe: 'tent' },
    { selected: '', shouldBe: 'grass' },
    { selected: '', shouldBe: 'grass' },
    { selected: '', shouldBe: 'grass' },
    { selected: '', shouldBe: 'grass' },
    { selected: 'tree' },
  ],
  [
    { selected: '', shouldBe: 'grass' },
    { selected: '', shouldBe: 'grass' },
    { selected: 'tree' },
    { selected: '', shouldBe: 'grass' },
    { selected: '', shouldBe: 'grass' },
    { selected: '', shouldBe: 'tent' },
    { selected: 'tree' },
    { selected: '', shouldBe: 'tent' },
  ],
  [
    { selected: '', shouldBe: 'tent' },
    { selected: '', shouldBe: 'grass' },
    { selected: '', shouldBe: 'tent' },
    { selected: '', shouldBe: 'grass' },
    { selected: '', shouldBe: 'grass' },
    { selected: '', shouldBe: 'grass' },
    { selected: '', shouldBe: 'grass' },
    { selected: '', shouldBe: 'grass' },
  ],
  [
    { selected: 'tree' },
    { selected: '', shouldBe: 'grass' },
    { selected: '', shouldBe: 'grass' },
    { selected: '', shouldBe: 'grass' },
    { selected: '', shouldBe: 'tent' },
    { selected: '', shouldBe: 'grass' },
    { selected: '', shouldBe: 'grass' },
    { selected: '', shouldBe: 'grass' },
  ],
  [
    { selected: '', shouldBe: 'grass' },
    { selected: '', shouldBe: 'tent' },
    { selected: 'tree' },
    { selected: '', shouldBe: 'grass' },
    { selected: 'tree' },
    { selected: '', shouldBe: 'grass' },
    { selected: 'tree' },
    { selected: '', shouldBe: 'tent' },
  ],
  [
    { selected: '', shouldBe: 'grass' },
    { selected: '', shouldBe: 'grass' },
    { selected: '', shouldBe: 'grass' },
    { selected: '', shouldBe: 'grass' },
    { selected: '', shouldBe: 'tent' },
    { selected: 'tree' },
    { selected: '', shouldBe: 'grass' },
    { selected: '', shouldBe: 'grass' },
  ],
];
